PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE Categories(id INTEGER PRIMARY KEY, name TEXT, image TEXT);
INSERT INTO "Categories" VALUES(1,'Posted a cringy picture of yourself online','cringe.jpg');
INSERT INTO "Categories" VALUES(2,'Sent a drunk message/post','drunk.jpg');
INSERT INTO "Categories" VALUES(3,'Sent an angry message/post','angry.jpg');
INSERT INTO "Categories" VALUES(4,'Insulted someone publicly using social media','insult.jpg');
INSERT INTO "Categories" VALUES(5,'Argued in the comments section of an article/video','argue.jpg');
INSERT INTO "Categories" VALUES(6,'Shared a pic or video of you doing something stupid','stupid.jpg');
INSERT INTO "Categories" VALUES(7,'Shared a pic or video of someone else doing something stupid','photo_fall.jpg');
INSERT INTO "Categories" VALUES(8,'Shared a naked picture of yourself','naked.jpg');
INSERT INTO "Categories" VALUES(9,'Shared a naked picture of someone else','photo_naked.jpg');
INSERT INTO "Categories" VALUES(10,'Dumped someone by text/messaging/public posting','sad.jpg');
INSERT INTO "Categories" VALUES(11,'Searched for someone but posted their name by mistake','search.jpg');
INSERT INTO "Categories" VALUES(12,'Sent a flirtatious text to the wrong person','hi.jpg');
INSERT INTO "Categories" VALUES(13,'Accidentally shared porn or rude pics','porn.jpg');
INSERT INTO "Categories" VALUES(14,'Accidentally stumbled across porn','porn.jpg');
CREATE TABLE Confessions(id INTEGER PRIMARY KEY, id_category INT, text TEXT, score INT);
INSERT INTO "Confessions" VALUES(1,1,'This is a sample confession. Please delete me.',1);
INSERT INTO "Confessions" VALUES(2,2,'This is a sample confession. Please delete me.',1);
INSERT INTO "Confessions" VALUES(3,3,'This is a sample confession. Please delete me.',1);
INSERT INTO "Confessions" VALUES(4,4,'This is a sample confession. Please delete me.',1);
INSERT INTO "Confessions" VALUES(5,5,'This is a sample confession. Please delete me.',1);
INSERT INTO "Confessions" VALUES(6,6,'This is a sample confession. Please delete me.',1);
INSERT INTO "Confessions" VALUES(7,7,'This is a sample confession. Please delete me.',1);
INSERT INTO "Confessions" VALUES(8,8,'This is a sample confession. Please delete me.',1);
INSERT INTO "Confessions" VALUES(9,9,'This is a sample confession. Please delete me.',1);
INSERT INTO "Confessions" VALUES(10,10,'This is a sample confession. Please delete me.',1);
INSERT INTO "Confessions" VALUES(11,11,'This is a sample confession. Please delete me.',1);
INSERT INTO "Confessions" VALUES(12,12,'This is a sample confession. Please delete me.',1);
INSERT INTO "Confessions" VALUES(13,13,'This is a sample confession. Please delete me.',1);
INSERT INTO "Confessions" VALUES(14,14,'This is a sample confession. Please delete me.',1);
COMMIT;
