PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE Categories(id INTEGER PRIMARY KEY, name TEXT, image TEXT);
INSERT INTO "Categories" VALUES(1,'Posted a cringy picture of yourself online','cringe.jpg');
INSERT INTO "Categories" VALUES(2,'Sent a drunk message/post','drunk.jpg');
INSERT INTO "Categories" VALUES(3,'Sent an angry message/post','angry.jpg');
INSERT INTO "Categories" VALUES(4,'Insulted someone publicly using social media','insult.jpg');
INSERT INTO "Categories" VALUES(5,'Argued in the comments section of an article/video','argue.jpg');
INSERT INTO "Categories" VALUES(6,'Shared a pic or video of you doing something stupid','stupid.jpg');
INSERT INTO "Categories" VALUES(7,'Shared a pic or video of someone else doing something stupid','photo_fall.jpg');
INSERT INTO "Categories" VALUES(8,'Shared a naked picture of yourself','naked.jpg');
INSERT INTO "Categories" VALUES(9,'Shared a naked picture of someone else','photo_naked.jpg');
INSERT INTO "Categories" VALUES(10,'Dumped someone by text/messaging/public posting','sad.jpg');
INSERT INTO "Categories" VALUES(11,'Searched for someone but posted their name by mistake','search.jpg');
INSERT INTO "Categories" VALUES(12,'Sent a flirtatious text to the wrong person','hi.jpg');
INSERT INTO "Categories" VALUES(13,'Accidentally shared porn or rude pics','porn.jpg');
INSERT INTO "Categories" VALUES(14,'Accidentally stumbled across porn','porn.jpg');
CREATE TABLE Confessions(id INTEGER PRIMARY KEY, id_category INT, text TEXT, score INT);
INSERT INTO "Confessions" VALUES(1,1,'Took a picture of my cat sitting on my face. Called it a ''catbeard''.',1);
INSERT INTO "Confessions" VALUES(2,2,'Emailed a boss while drunk. Said some bad things. Got called into her office the next day. Thought I was getting fired. As I stepped into the office, I found friends and coworkers sitting in chairs around the perimeter. "Thank God," I said, because I knew right away they don''t fire people in front of an audience. It was an intervention. Turned out to be the kindest thing anyone''s ever done for me. Sober 11 years and counting.',1);
INSERT INTO "Confessions" VALUES(3,3,'Sent an email in ALL CAPS when I was so angry about something. Shameful.
',1);
INSERT INTO "Confessions" VALUES(4,4,'Over a year ago I commented on a Justin Bieber video on YouTube saying he''s awful at singing and looks like a gargoyle. To this day I still get comments that are completely ridiculous and that barely pass as being in English.',1);
INSERT INTO "Confessions" VALUES(5,5,'Do this on TheJournal all the time. Great way to spend an afternoon.',1);
INSERT INTO "Confessions" VALUES(6,6,'Did a neknomination drinking a beer with a goldfish in it. Not my finest hour.',1);
INSERT INTO "Confessions" VALUES(7,7,'Shared the RTE news clip of the man slipping on the ice in Dublin. Still laugh every time I watch it.',1);
INSERT INTO "Confessions" VALUES(8,8,' Tried to send my husband a picture of my tits. Accidentally uploaded to Facebook.',1);
INSERT INTO "Confessions" VALUES(9,9,'Not telling you who it was.',1);
INSERT INTO "Confessions" VALUES(10,10,'Sent my girlfriend a text message saying that It''s over. Then changed my mind so sent a next message saying ''there'', pretending I was texting someone else about something they were looking for. ',1);
INSERT INTO "Confessions" VALUES(11,11,'Thought I was looking up my ex-boyfriend, but put his name in the status bar instead.',1);
INSERT INTO "Confessions" VALUES(12,12,' When I was immature and Myspace was a thing, I sometimes sent creepy stalker-ish messages to a crush without realizing how creepy I was being.',1);
INSERT INTO "Confessions" VALUES(13,13,'Accidentally +1''d a porn site on Google+',1);
INSERT INTO "Confessions" VALUES(14,14,'If you are going to look up information regarding the iconic actor Gary Oldman, make sure you include the letter ''r'' in his name when googling. This is doubly important if you are searching from work.',1);
INSERT INTO "Confessions" VALUES(15,8,'Sent a picture of my penis to my ex-girlfriend. She posted it everywhere when we broke up.',1);
INSERT INTO "Confessions" VALUES(16,13,'I printed some pretty niche fetish stories on my family computer. They never printed....oh wait, they did, later on, while my father was standing next to the printer, talking to my sister.',1);
INSERT INTO "Confessions" VALUES(17,14,'When dicks sporting goods came to my area a couple years ago, my mom and I tried to get on their website and without thinking went to dicks.com. Was a very awkward moment',1);
INSERT INTO "Confessions" VALUES(18,14,' I remember in sixth grade (before all this web blocker business) my friends and I were trying to find new websites by entering random words into the url field: manhole.com is NOT a website selling sewer access caps.',1);
INSERT INTO "Confessions" VALUES(19,14,' When I was about 15, after discovering I could download porn I spent about 2 hours watching it on iTunes, with a playlist full of raunchy, dodgy titles. During this time, someone popped up on MSN Messenger saying "Little early isn''t it mate?" - I''d left my ''What I''m listening to'' feature enabled.',1);
COMMIT;
